export enum VoucherStatusEnum {
  POSTED = "POSTED",
  REVERSED = "REVERSED"
}

export enum LedgerPostingEventEnum {
  PAYROLL_RUN_FINALIZED = "PAYROLL_RUN_FINALIZED",
  INVESTMENT_PURCHASE = "INVESTMENT_PURCHASE",
  ASSET_CAPITALIZATION = "ASSET_CAPITALIZATION",
  STATIONERY_ISSUE = "STATIONERY_ISSUE",
  SHARE_ALLOTMENT = "SHARE_ALLOTMENT"
}
