export const PERMISSIONS = {
  DASHBOARD_READ: "dashboard.read",
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_DELETE: "users.delete",
  BRANCHES_READ: "branches.read",
  BRANCHES_CREATE: "branches.create",
  BRANCHES_UPDATE: "branches.update",
  BRANCHES_DELETE: "branches.delete",
  DEPARTMENTS_READ: "departments.read",
  DEPARTMENTS_CREATE: "departments.create",
  DEPARTMENTS_UPDATE: "departments.update",
  DEPARTMENTS_DELETE: "departments.delete",
  DESIGNATIONS_READ: "designations.read",
  DESIGNATIONS_CREATE: "designations.create",
  DESIGNATIONS_UPDATE: "designations.update",
  DESIGNATIONS_DELETE: "designations.delete",
  COST_CENTERS_READ: "costCenters.read",
  COST_CENTERS_CREATE: "costCenters.create",
  COST_CENTERS_UPDATE: "costCenters.update",
  COST_CENTERS_DELETE: "costCenters.delete",
  AUDIT_LOGS_READ: "auditLogs.read"
} as const;
